In [5]:
import pandas as pd
from pathlib import Path
from omegaconf import OmegaConf, DictConfig

In [2]:
from moviepy.editor import VideoFileClip
import pysrt
from datetime import timedelta

In [3]:
def get_video_info(video_file):
    """获取视频时长和帧数"""
    clip = VideoFileClip(video_file)
    duration = clip.duration  # 视频时长（秒）
    fps = clip.fps  # 帧率
    resolution = clip.size
    return duration, fps, resolution

In [6]:
demo_data_path = OmegaConf.load('../configs/demo_data_path.yaml')

video_path_str = demo_data_path['video_path_str']
audio_path_str = demo_data_path['audio_path_str']
subtitle_path_str = demo_data_path['subtitle_path_str']

video_eg_path_str = demo_data_path['video_eg_path_str']
subtitle_eg_path_str = demo_data_path['subtitle_eg_path_str']
audio_eg_path_str = demo_data_path['audio_eg_path_str']

In [5]:
subtitle_eg_path_str

'D:\\dcmt\\code\\python\\playground\\sample_videos\\subtitle\\renminribao\\7183343454993485115.srt'

In [16]:
def print_fps(video_path_str):
    video_path = Path(video_path_str)
    for file in video_path.glob("*.mp4"):
        print(file.name)
        print(get_video_info(str(file)))

print_fps(video_path_str)

7183343454993485115.mp4
(7.89, 25.0, [576, 1024])
7185030947190967555.mp4
(18.37, 25.0, [540, 960])
7185400788041108796.mp4
(17.13, 25.0, [576, 1024])
7186896342118124855.mp4
(20.65, 25.0, [576, 1024])
7187017932747148581.mp4
(7.57, 25.0, [576, 1024])
7187268299481255224.mp4
(20.37, 25.0, [576, 1024])
7187702569005796664.mp4
(15.17, 25.0, [576, 1024])
7187939898882592061.mp4
(15.3, 25.0, [576, 1024])
7188048383486070073.mp4
(15.72, 25.0, [576, 1024])
7188734037094141240.mp4
(13.33, 25.0, [576, 1024])
7189119505803562299.mp4
(18.5, 25.0, [576, 1024])
7190945066020605241.mp4
(22.5, 30.0, [1080, 1080])
7191042774752431421.mp4
(29.74, 25.0, [576, 1024])
7191689335454862629.mp4
(16.77, 25.0, [576, 1024])
7192841773159353655.mp4
(18.14, 25.0, [576, 1024])
7193607840253119801.mp4
(7.77, 25.0, [576, 1024])
7193908157880618277.mp4
(17.05, 25.0, [540, 960])
7194736398417628473.mp4
(22.38, 25.0, [540, 960])
7194740066390969656.mp4
(27.56, 25.0, [576, 1024])
7194741228817108279.mp4
(27.61, 25.0, [

In [21]:
subs = pysrt.open(subtitle_eg_path_str)

In [ ]:
for sub in subs:
    print(sub)

In [25]:
for sub in subs:
    print(sub)
    print(sub.start)
    print(sub.end)
    print(sub.text)
    break

1
00:00:00,040 --> 00:00:01,040
人客户端 你好 中国航天
S

00:00:00,040
00:00:01,040
人客户端 你好 中国航天
S


In [31]:
def get_subtitle_at_time(srt_file, target_time):
    subtitles = pysrt.open(srt_file)

    for subtitle in subtitles:
        # 检查字幕是否在指定时间点内
        if subtitle.start <= target_time <= subtitle.end:
            return subtitle.text
    return None  # 如果没有找到对应的字幕

In [44]:
get_subtitle_at_time(subtitle_eg_path_str, pysrt.SubRipTime(seconds=5))

'你好 中国航天'

In [5]:
def extract_frames(video_path, timestamps):
    # 加载视频文件
    clip = VideoFileClip(video_path)
    frames = []

    # 遍历给定的时间戳
    for timestamp in timestamps:
        # 获取视频帧并转换为 numpy 数组
        frame = clip.get_frame(timestamp)
        frames.append(frame)

    return frames

In [8]:
eg_frames = extract_frames(video_eg_path_str, [1, 2, 3])

In [10]:
eg_frames[0].shape

(1024, 576, 3)

In [11]:
def get_subtitles_at_times(srt_file, target_times):
    subtitles = pysrt.open(srt_file)
    results = []

    for target_time in target_times:
        found_subtitle = None
        for subtitle in subtitles:
            # 检查字幕是否在指定时间点内
            if subtitle.start <= target_time <= subtitle.end:
                found_subtitle = subtitle.text
                break
        results.append(found_subtitle)
    return results


In [12]:
get_subtitles_at_times(subtitle_eg_path_str, [pysrt.SubRipTime(seconds=5), pysrt.SubRipTime(seconds=10)])

['你好 中国航天', None]

In [1]:
import torchaudio

In [2]:
waveform, sample_rate = torchaudio.load(r"D:\dcmt\dataset\news_emotion\audio\7183343024657747258.wav", format="wav")

In [3]:
sample_rate

44100

In [3]:
waveform

tensor([[ 0.0004,  0.0038,  0.0017,  ..., -0.0005, -0.0007, -0.0004],
        [-0.0003,  0.0036,  0.0032,  ..., -0.0005, -0.0005, -0.0005]])

In [4]:
from embedding import AudioEncoder

C:\Users\32066\anaconda3\envs\dl_env\Lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\32066\anaconda3\envs\dl_env\Lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(


In [5]:
audio_encoder = AudioEncoder()

Some weights of Wav2Vec2Model were not initialized from the model checkpoint at D:\dcmt\model\hf\facebook\wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [6]:
from audio import Audio

In [7]:
audio = Audio('7184773290962013477')

In [8]:
audio.load_audio()

(tensor([[ 0.0017,  0.0021,  0.0003,  ..., -0.0010, -0.0006, -0.0002],
         [ 0.0027,  0.0024,  0.0011,  ..., -0.0009, -0.0006, -0.0007]]),
 44100)

In [9]:
outputs = audio_encoder.encode(audio.load_audio())

In [10]:
outputs

tensor([[[-0.0413,  0.0178, -0.0867,  ..., -0.1289,  0.0927,  0.0659],
         [-0.0697,  0.0205, -0.0741,  ..., -0.1732,  0.1051,  0.1955],
         [-0.0769,  0.0933, -0.1474,  ..., -0.2412, -0.0473,  0.2337],
         ...,
         [ 0.0025,  0.0037,  0.1290,  ..., -0.1023,  0.0049, -0.0734],
         [ 0.0021,  0.0030,  0.1314,  ..., -0.1019,  0.0046, -0.0727],
         [ 0.0027,  0.0013,  0.1332,  ..., -0.0974,  0.0067, -0.0726]]])

In [11]:
outputs.shape

torch.Size([1, 1023, 768])

In [12]:
outputs.last_hidden_state.shape

torch.Size([1, 1023, 768])

In [13]:
outputs.last_hidden_state

tensor([[[-0.0351,  0.0408, -0.0498,  ..., -0.1647,  0.0480,  0.1014],
         [-0.0523,  0.0639, -0.0574,  ..., -0.1867,  0.0335,  0.1464],
         [-0.0605,  0.0929, -0.0763,  ..., -0.1656, -0.0286,  0.0970],
         ...,
         [-0.0497, -0.0238,  0.1838,  ..., -0.0295,  0.0092, -0.0320],
         [-0.0491, -0.0168,  0.1747,  ..., -0.0360,  0.0050, -0.0207],
         [-0.0464, -0.0261,  0.1861,  ..., -0.0311,  0.0079, -0.0329]]])

In [14]:
outputs.extract_features.shape

torch.Size([1, 1023, 512])

In [1]:
from embedding import TextEncoder

C:\Users\32066\anaconda3\envs\dl_env\Lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(


In [2]:
text_encoder = TextEncoder()

In [12]:
text_outputs = text_encoder.encode("喂喂喂，你是谁？ How are you?今天是星期五")

In [13]:
text_outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1809,  0.1997,  0.1070,  ..., -0.1597,  0.1561,  0.0613],
         [-0.0161,  0.0260, -0.0173,  ...,  0.2677,  0.0796,  0.0349],
         [-0.0166,  0.1278,  0.0090,  ...,  0.1307,  0.0132,  0.2803],
         ...,
         [ 0.1851,  0.1969, -0.0150,  ..., -0.3778,  0.0088,  0.1690],
         [ 0.1851,  0.1969, -0.0150,  ..., -0.3778,  0.0088,  0.1690],
         [ 0.1851,  0.1969, -0.0150,  ..., -0.3778,  0.0088,  0.1690]]]), pooler_output=tensor([[-8.5511e-02,  2.1308e-01,  5.7061e-02,  6.2184e-01,  1.2262e-01,
          3.9616e-01,  3.8524e-01, -2.7557e-01,  2.7607e-01, -1.0120e-01,
         -1.1621e-01,  1.9004e-01,  2.7817e-01,  4.2877e-01, -3.9401e-01,
         -2.1357e-01,  3.8656e-01,  3.2845e-01,  6.7676e-02, -2.0997e-01,
         -4.7521e-01,  5.0064e-01, -7.2294e-01, -6.2276e-01, -2.9578e-01,
          6.3506e-01,  1.1181e-01, -2.3934e-01, -6.1055e-02,  6.9680e-01,
          2.7042e-01,  4.7691e-01, -

In [14]:
text_outputs.last_hidden_state.shape

torch.Size([1, 128, 768])

In [11]:
text_outputs.pooler_output.shape

torch.Size([1, 768])